assignment: 노욱진
dogVelopers/2022_FE_React_03 pull request #2
Opened 2022-06-01 13:42 UTC by NohWookJin

https://fmmn5b.csb.app/

2022-06-09 06:23 UTC, hyesungoh requested changes
작업해주신 내용 잘봤어요! 컴포넌트로 분리하시는 관점이 좋은 것 같아요 👍 👍 

하지만 다소 과제 출제 의도와 어긋나는 부분이 있는데 일단 꼭 수정해주셨으면 하는 부분은, 

1. 현재 두가지 상태로 (댓글 제목 배열, 댓글 내용 배열)로 관리하는 것을 1가지 상태로 관리하는 방향으로 바꿔주세요.

2. 변수 혹은 함수의 이름을 조금 더 명시적으로 바꿔주세요. 

다음주 목요일 (16일)까지만 과제 업데이트 해주시면 좋을 거 같아요 ~!

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Header.tsx
> +    <div className="header">
```suggestion
    <header className="header">
```

해당 부분과 함께 다른 부분에서도 `main`, `aside`, `section`, `article`과 같은 **시맨틱 태그**에 대해 공부해보시면 좋을 거 같아요!

https://developer.mozilla.org/ko/docs/Glossary/Semantics

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Comment.tsx
> +    setState("댓글");
현재 댓글을 추가할 때, 텍스트가 변경되고 있어요.

이럴 경우, 만약 댓글을 서버에서 응답 받은 값으로 렌더링된다고 할 때 이미 댓글이 있어도 '첫 댓글을 남겨주세요'가 나오게 될 거 같아요

댓글을 추가할 때의 로직이 아닌, 댓글의 갯수로 판단하는 로직이 직관적일 거 같아요

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Comment.tsx
> +  let [state, setState] = useState<string>("첫 댓글을 남겨주세요 ");
해당 상태 (state)는 댓글의 개수에 따라 보여지는 텍스트를 저장하는 상태로 확인돼요.

근데 state란 이름은 다소 비적절하다고 생각돼용

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Comment.tsx
> +  let [textContentValue, setTextContentValue] = useState<string>("");
모두 let으로 선언하신 이유가 있으실까요?

state의 경우 직접 대입이 일어나면 안됩니다. 항상 const로 선언해주세요

> 추가적으로 모든 변수들을 const로 선언하시고 재할당이 일어날 때만 let으로 바꿔주시는 방법을 권장드려요

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Comment.tsx
> +  }
함수 명을 숫자로 구분하는 것보다 분류에 따라 이름을 붙혀주시는 게 좋을 거 같아요

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Chat.tsx
> +function Chat({ textName, textContent }: Comment) {
props로 주입받아 렌더링하는 방법은 매우 좋아요

하지만 현재 `Comment`에서 관리하고 있는 댓글의 경우 

`제목 배열`. `내용 배열`로 관리되어 두 스트링 배열을 props로 받는 것으로 보여요

이렇게 핸들링 하는 것보다, 한 가지 object 배열 state로 제목과 내용을 가지고 있는 형태를 권장해요

2022-06-09 06:23 UTC, hyesungoh commented on src/components/Chat.tsx
> +      {textName.map((i, a) => {
```suggestion
      {textName.map((eachComment, index) => {
```

예시로써 위처럼 명시적으로 이름을 짓는 건 어떨까요?

2022-06-13 12:49 UTC, NohWookJin commented on src/components/Chat.tsx
> +function Chat(props: any) {
인터페이스로 comments를 string[] 타입으로 선언하려고 했는데, map 함수가 comments가 배열이 아니라고 에러가 떠서 결국 직접적으로 props를 넣었습니다.. eachComment 부분도 타입설정을 하라고 하길래 일단 any 타입으로 설정했습니다... 다 any 타입으로 설정안하면 자꾸 에러가 나는데, 원인을 모르겠습니다...ㅜ

2022-06-14 03:34 UTC, hyesungoh requested changes

2022-06-14 03:34 UTC, hyesungoh commented on src/components/Comment.tsx
> +interface CommentBox {
요 interface를 export 후,

2022-06-14 03:34 UTC, hyesungoh commented on src/components/Chat.tsx
> +function Chat(props: any) {
요기에서 사용하시면 돼요 ~~

```suggestion
import {CommentBox} from '코멘트.tsx 위치';

interface ChatProps {
  Comments: CommentBox[];
}

function Chat(props: any) {
```

2022-06-14 03:36 UTC, hyesungoh commented on src/components/Chat.tsx
> +function Chat(props: any) {
지금 propr로 받고 있는 것의 type이 뭔지 생각해보시면 돼요! 

사용하고 있는 곳에서 주입하고 있는 props가 

```ts
  const [comments, setComments] = useState<CommentBox[]>([]);
```

요 친구이니 요 친구의 type으로 선언하면 됩니다 ~

2022-06-14 06:42 UTC, NohWookJin commented on src/components/Chat.tsx
> +function Chat(props: any) {
감사합니다! 해결 바로 됐습니다.. ㅜ
피드백 받은 걸로 다시 수정해서 PR 날릴게요~!
(항상 피드백 감사합니다..)

2022-06-14 14:49 UTC, hyesungoh reviewed
👍 👍 👍 👍  `rem`으로 작성하시는 모습 좋아요 ~~!

2022-06-14 14:49 UTC, hyesungoh commented on src/components/Chat.tsx
> +  Comments: CommentBox[];
요거는 관례상 소문자가 좋을 거 같아요 ~!

2022-06-16 09:17 UTC, hanseulhee commented on src/components/Header.tsx
> +      <h1 className="hello">WELC🙇‍♂️ME</h1>
이모티콘 센스 👍🏻👍🏻👍🏻
클래스 명을 더 자세히 적어도 좋을 것 같아요 !!

2022-06-16 09:17 UTC, hanseulhee commented on src/components/Header.tsx
> +          <span>🐢 느리지만 열심히 배우려고 노력하고 있습니다 </span>
Fighting !!!!!!

2022-06-16 09:17 UTC, hanseulhee commented on src/css/Category.css
> +.bookmark button:nth-of-type(2) {
이런 기능이 있군요 배우고 갑니다 😮

2022-06-16 09:17 UTC, hanseulhee commented on src/css/Comments.css
> +  border: none;
아실 수도 있지만 all: unset 하시면 기본 스타일을 초기화할 수 있어요!

2022-06-19 06:42 UTC, NohWookJin commented on src/App.css
>  }
test

2023-04-29 06:42 UTC, closed without merging